version: 0.0
environment_variables:
    plaintext:
        "INPUT_FILE": "saml.yaml"
        "S3_BUCKET": ""
containers:
    LambdaFunctions:
        phases:
            during_build:
                commands:
                    - npm install
                    - aws cloudformation package --template DynamoDB_Table.yaml --s3-bucket $S3_BUCKET --output-template DBpost-saml.yaml
                    - aws cloudformation package --template $INPUT_FILE --s3-bucket $S3_BUCKET --output-template post-saml.yaml
                    
        artifacts:
            files:
                - DBpost-saml.yaml
                - post-saml.yaml
                - beta.json
